"""Derive every logo asset from one geometric definition.

The mark is the smallest graph there is: three solid nodes on an equilateral
triangle, joined by three edges. One node carries the brand blue; the other
two and the edges carry the ink. It is defined here as geometry rather than
traced from a bitmap, so every output is a true vector at heart and the whole
identity is one edit away from changing.

Run:  uv run python assets/_gen_logo_assets.py

Outputs (all regenerated, never hand-edited):

    assets/logo.svg            two-tone, ink + blue, for light grounds
    assets/logo-light.svg      two-tone, mist + blue, for dark grounds
    assets/logo.png            as logo.svg, transparent, 1024 px
    assets/logo-light.png      as logo-light.svg, transparent, 1024 px
    assets/logo-banner.svg     mark + wordmark, light scheme
    assets/logo-banner-dark.svg
    docs/logo.svg              single ink, for the blue docs header
    docs/logo-ink.svg          two-tone, for the light docs hero
    docs/logo-light.svg        two-tone, for the dark docs hero
    docs/favicon.png           ink mark on a blue plate

The header needs its own single-ink mark because it is painted in the brand
blue, where the blue node would vanish.

Design constraints that the numbers below encode:

* **One stroke weight.**  All three edges share ``STROKE``.
* **Edges stop short of nodes.**  Each segment is trimmed by the node radius
  plus ``GAP``, so the nodes stay legible as discrete vertices instead of
  fusing into the lines at favicon sizes.
* **Optical centring.**  The triangle is placed so its bounding box, nodes
  included, is centred in the design box, not its centroid; a centroid-centred
  triangle looks like it is sinking.
"""

from __future__ import annotations

import math
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]

# The brand blue and the two inks drawn from its hue (209.5 deg).
BLUE = "#8da9c4"
INK = "#111a22"  # 7.2:1 on BLUE, 17.6:1 on white
MIST = "#f2f5f8"  # the light ink, for dark grounds

# ------------------------------------------------------------------ #
# Mark geometry, in a 120x120 design box.                             #
# ------------------------------------------------------------------ #
BOX = 120
NODE_R = 17.0  # every node is a solid disc of this radius
STROKE = 9.0  # the single edge weight
GAP = 5.0  # clear space between a node's edge and an incident edge
SIDE = 82.0  # triangle side, centre to centre

_H = SIDE * math.sqrt(3) / 2
_TOP_Y = (BOX - (_H + 2 * NODE_R)) / 2 + NODE_R
NODES: dict[str, tuple[float, float]] = {
    "top": (BOX / 2, round(_TOP_Y, 2)),
    "left": (round(BOX / 2 - SIDE / 2, 2), round(_TOP_Y + _H, 2)),
    "right": (round(BOX / 2 + SIDE / 2, 2), round(_TOP_Y + _H, 2)),
}
EDGES = [("top", "left"), ("top", "right"), ("left", "right")]
ACCENT = "top"  # the node drawn in the brand blue

# A round cap projects STROKE/2 past the endpoint, so pull back by that too.
TRIM = NODE_R + GAP + STROKE / 2


def _hex(value: str) -> tuple[int, int, int]:
    v = value.lstrip("#")
    return tuple(int(v[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]


def segments() -> list[tuple[float, float, float, float]]:
    """The three edges, each trimmed back to clear both of its endpoints."""
    out = []
    for a, b in EDGES:
        (x1, y1), (x2, y2) = NODES[a], NODES[b]
        dx, dy = x2 - x1, y2 - y1
        length = math.hypot(dx, dy)
        ux, uy = dx / length, dy / length
        out.append(
            (
                round(x1 + ux * TRIM, 2),
                round(y1 + uy * TRIM, 2),
                round(x2 - ux * TRIM, 2),
                round(y2 - uy * TRIM, 2),
            )
        )
    return out


# ------------------------------------------------------------------ #
# SVG                                                                 #
# ------------------------------------------------------------------ #
def mark_svg_body(ink: str, accent: str, indent: str = "  ") -> str:
    """The mark's SVG elements, in the 120x120 design box."""
    lines = [f'{indent}<g stroke="{ink}" stroke-width="{STROKE}" stroke-linecap="round">']
    for x1, y1, x2, y2 in segments():
        lines.append(f'{indent}  <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}"/>')
    lines.append(f"{indent}</g>")
    for name, (cx, cy) in NODES.items():
        fill = accent if name == ACCENT else ink
        lines.append(f'{indent}<circle cx="{cx}" cy="{cy}" r="{NODE_R}" fill="{fill}"/>')
    return "\n".join(lines)


def write_mark_svg(ink: str, accent: str, path: Path) -> None:
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {BOX} {BOX}" width="{BOX}" height="{BOX}" role="img" aria-label="graphnetz">
  <title>graphnetz</title>
  <!-- Generated by assets/_gen_logo_assets.py; do not edit by hand. -->
{mark_svg_body(ink, accent)}
</svg>
"""
    path.write_text(svg)


# Banner layout. The mark is scaled into a 64 px square at the left, the
# wordmark sits on the mark's optical centreline.
WORD = "graphnetz"
BANNER_H = 88
MARK_PX = 64
MARK_XY = (8, 12)
TEXT_X = 88
TEXT_SIZE = 42
TEXT_BASELINE = 58
TEXT_TRACKING = -0.8
# Mean bold glyph advance for "graphnetz", in em, in the *fallback* face
# (Helvetica/Arial): GitHub renders the SVG in an <img> sandbox where a
# webfont cannot load, so the fallback is what actually sets the width.
ADVANCE = 0.531
BANNER_W = round(TEXT_X + len(WORD) * (TEXT_SIZE * ADVANCE + TEXT_TRACKING) + 12)


def write_banner_svg(ink: str, accent: str, path: Path) -> None:
    """Mark + wordmark, as pure vector."""
    scale = MARK_PX / BOX
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {BANNER_W} {BANNER_H}" width="{BANNER_W}" height="{BANNER_H}" role="img" aria-label="{WORD}">
  <title>{WORD}</title>
  <!-- Generated by assets/_gen_logo_assets.py; do not edit by hand. -->
  <g transform="translate({MARK_XY[0]},{MARK_XY[1]}) scale({scale:.6f})">
{mark_svg_body(ink, accent, indent="    ")}
  </g>
  <text x="{TEXT_X}" y="{TEXT_BASELINE}" font-family="Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="{TEXT_SIZE}" font-weight="700" fill="{ink}" letter-spacing="{TEXT_TRACKING}">{WORD}</text>
</svg>
"""
    path.write_text(svg)


# ------------------------------------------------------------------ #
# PNG                                                                 #
# ------------------------------------------------------------------ #
SS = 4  # supersample factor; PIL's draw primitives do not antialias


def _round_line(draw: ImageDraw.ImageDraw, seg, ink, width: float) -> None:
    """A line with round caps, which ImageDraw does not provide natively."""
    x1, y1, x2, y2 = seg
    draw.line([(x1, y1), (x2, y2)], fill=ink, width=round(width))
    r = width / 2
    for cx, cy in ((x1, y1), (x2, y2)):
        draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=ink)


def render(ink: str, accent: str, size: int) -> Image.Image:
    """The mark on transparency, at ``size`` px square."""
    big = size * SS
    img = Image.new("RGBA", (big, big), (*_hex(ink), 0))
    draw = ImageDraw.Draw(img)
    k = big / BOX
    for x1, y1, x2, y2 in segments():
        _round_line(draw, (x1 * k, y1 * k, x2 * k, y2 * k), (*_hex(ink), 255), STROKE * k)
    for name, (cx, cy) in NODES.items():
        fill = (*_hex(accent if name == ACCENT else ink), 255)
        r = NODE_R * k
        draw.ellipse([cx * k - r, cy * k - r, cx * k + r, cy * k + r], fill=fill)
    return img.resize((size, size), Image.LANCZOS)


def plated(ink: str, plate: str, size: int) -> Image.Image:
    """The single-ink mark on an opaque rounded plate, for favicon legibility.

    A transparent favicon disappears against a tab bar that happens to match
    the ink, so the icon carries its own background.
    """
    out = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    radius = int(size * 0.22)
    ImageDraw.Draw(out).rounded_rectangle([0, 0, size - 1, size - 1], radius, fill=(*_hex(plate), 255))
    mark = render(ink, ink, int(size * 0.74))
    off = (size - mark.width) // 2
    out.alpha_composite(mark, (off, off))
    return out


def main() -> None:
    svgs = [
        (ROOT / "assets" / "logo.svg", INK, BLUE, write_mark_svg),
        (ROOT / "assets" / "logo-light.svg", MIST, BLUE, write_mark_svg),
        (ROOT / "assets" / "logo-banner.svg", INK, BLUE, write_banner_svg),
        (ROOT / "assets" / "logo-banner-dark.svg", MIST, BLUE, write_banner_svg),
        (ROOT / "docs" / "logo.svg", INK, INK, write_mark_svg),
        (ROOT / "docs" / "logo-ink.svg", INK, BLUE, write_mark_svg),
        (ROOT / "docs" / "logo-light.svg", MIST, BLUE, write_mark_svg),
    ]
    for path, ink, accent, writer in svgs:
        writer(ink, accent, path)
        print(f"  wrote {path.relative_to(ROOT)}  {path.stat().st_size} B")

    pngs = [
        (ROOT / "assets" / "logo.png", render(INK, BLUE, 1024)),
        (ROOT / "assets" / "logo-light.png", render(MIST, BLUE, 1024)),
        (ROOT / "docs" / "favicon.png", plated(INK, BLUE, 512)),
    ]
    for path, img in pngs:
        img.save(path, format="PNG", optimize=True)
        print(f"  wrote {path.relative_to(ROOT)}  {img.size[0]}px  {path.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
