"""Derive every logo asset from one source image.

The source (``assets/logo-source.png``) is a black mark on an opaque white
square.  That cannot be used directly: on the docs' dark header it would show
as a white box, and the ink sits off-centre in the canvas.  This script keys
the white out to alpha, re-centres the mark, and tints it for each place it
appears.

Run:  uv run python assets/_gen_logo_assets.py

Outputs (all regenerated, never hand-edited):

    assets/logo.png            Carbon Black ink, transparent, 1024 px
    assets/logo-light.png      Bright Snow ink, transparent, 1024 px
    assets/logo-banner.svg     mark + wordmark, light scheme
    assets/logo-banner-dark.svg
    docs/logo.png              Bright Snow ink for the dark header/hero
    docs/favicon.png           Carbon Black on a Bright Snow plate

Keying uses luminance as alpha rather than a colour-match threshold, so the
mark's anti-aliased edges survive intact instead of going jagged.
"""

from __future__ import annotations

import base64
import io
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "logo-source.png"

# graphnetz.plotting.BRAND_COLORS
SNOW = "#f8f9fa"
CARBON = "#212529"

PAD = 0.06  # margin around the mark, as a fraction of the square


def _hex(value: str) -> tuple[int, int, int]:
    v = value.lstrip("#")
    return tuple(int(v[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]


def load_mark() -> Image.Image:
    """Return the mark as an alpha-keyed, trimmed, centred RGBA square.

    ``alpha = 255 - luminance`` turns a black-on-white bitmap into a stencil,
    which keeps every anti-aliased edge pixel at its correct partial opacity.
    """
    rgb = np.asarray(Image.open(SOURCE).convert("RGB"), dtype=np.float64)
    lum = 0.2126 * rgb[..., 0] + 0.7152 * rgb[..., 1] + 0.0722 * rgb[..., 2]
    alpha = np.clip(255.0 - lum, 0, 255).astype(np.uint8)

    stencil = Image.fromarray(alpha, mode="L")
    box = stencil.getbbox()
    if box is None:
        msg = f"{SOURCE} appears blank"
        raise ValueError(msg)
    stencil = stencil.crop(box)

    # Centre in a square with even padding on all sides.
    side = round(max(stencil.size) * (1 + 2 * PAD))
    canvas = Image.new("L", (side, side), 0)
    canvas.paste(stencil, ((side - stencil.width) // 2, (side - stencil.height) // 2))
    return canvas.convert("L")


def tinted(stencil: Image.Image, colour: str, size: int) -> Image.Image:
    """The stencil rendered in ``colour`` on transparency, at ``size`` px."""
    s = stencil.resize((size, size), Image.LANCZOS)
    out = Image.new("RGBA", (size, size), (*_hex(colour), 0))
    out.putalpha(s)
    return out


def plated(stencil: Image.Image, ink: str, plate: str, size: int) -> Image.Image:
    """The stencil on an opaque rounded plate, for favicon legibility.

    A transparent favicon disappears against a tab bar that happens to match
    the ink, so the icon carries its own background.
    """
    out = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    radius = int(size * 0.18)
    ImageDraw.Draw(out).rounded_rectangle([0, 0, size - 1, size - 1], radius, fill=(*_hex(plate), 255))
    mark = tinted(stencil, ink, int(size * 0.78))
    off = (size - mark.width) // 2
    out.alpha_composite(mark, (off, off))
    return out


def _banner(stencil: Image.Image, ink: str, hub: str, path: Path) -> None:
    """A 460x96 wordmark banner with the mark embedded as a data URI.

    The mark is embedded rather than referenced because GitHub renders an SVG
    in an ``<img>`` sandbox, where external references do not load.  It is
    downscaled first so the README stays light.
    """
    mark = tinted(stencil, ink, 176)
    buf = io.BytesIO()
    mark.save(buf, format="PNG", optimize=True)
    uri = "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 460 96" width="460" height="96" role="img" aria-label="GraphNetz">
  <title>GraphNetz</title>
  <!-- Generated by assets/_gen_logo_assets.py; do not edit by hand.
       Ink {ink} from graphnetz.plotting.BRAND_COLORS. -->
  <image x="10" y="12" width="72" height="72" href="{uri}"/>
  <g font-family="'Google Sans Flex', 'Helvetica Neue', Helvetica, Arial, sans-serif">
    <text x="96" y="65" font-size="60" font-weight="600" fill="{hub}" letter-spacing="-1.2">GraphNetz</text>
  </g>
</svg>
"""
    path.write_text(svg)


def main() -> None:
    stencil = load_mark()
    print(f"source {SOURCE.name}: keyed and centred to {stencil.size[0]}px square")

    jobs = [
        (ROOT / "assets" / "logo.png", tinted(stencil, CARBON, 1024)),
        (ROOT / "assets" / "logo-light.png", tinted(stencil, SNOW, 1024)),
        (ROOT / "docs" / "logo.png", tinted(stencil, SNOW, 512)),
        (ROOT / "docs" / "favicon.png", plated(stencil, CARBON, SNOW, 512)),
    ]
    for path, img in jobs:
        img.save(path, format="PNG", optimize=True)
        print(f"  wrote {path.relative_to(ROOT)}  {img.size[0]}px  {path.stat().st_size // 1024} KB")

    _banner(stencil, CARBON, CARBON, ROOT / "assets" / "logo-banner.svg")
    _banner(stencil, SNOW, SNOW, ROOT / "assets" / "logo-banner-dark.svg")
    for name in ("logo-banner.svg", "logo-banner-dark.svg"):
        p = ROOT / "assets" / name
        print(f"  wrote assets/{name}  {p.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
